name: test gcp

on:
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: write to file
        run: echo "Some text here." > myfile.txt
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./myfile.txt
          destination: ${{ secrets.GCP_BUCKET }}/myfile.txt